### ISSUE TITLE
Add support for Dependabot PRs that update multiple dependencies

### ISSUE THREAD

**Issue by ChristopherBeltran** [dangoslen/dependabot-changelog-helper#213]
Occasionally Dependabot will open up a PR that attempts to update multiple dependencies(In my experience I have only seen it attempt to update two dependencies, not sure if it will ever attempt more):
<img width="813" alt="Screenshot 2023-11-14 at 5 13 57 PM" src="https://github.com/dangoslen/dependabot-changelog-helper/assets/34382621/7e872e24-77e0-4eec-94f6-0fae6b9d488a">

These PRs will cause the action to fail with an error: `Unable to extract entry from pull request title!`

**Comment by dangoslen** [comment]
Thanks for raising this issue.

I've had this in the back of my mind since GitHub announced this capability
but haven't had time to dig into it.

I think the core change will be to move the text scraping to the
description and allow for multiple matches. I also think I'd want to change
the updater to keep an in-memory representation until all package updates
are processed vs. writing the file twice.

The hard part will be the scraping I think, but could be wrong.

Rambling a bit here, but I'll see if I can start looking into this by the
end of the week.

As always, I'm happy to review a PR if you'd like to take a crack at it!

**Comment by dangoslen** [comment]
@ChristopherBeltran is that PR you mentioned public by chance? Just wanting to dig a bit more into what the format/structure of everything looks like

**Comment by ChristopherBeltran** [comment]
@dangoslen It's not public unfortunately. But if there's anything specific I can pull from it that could be helpful I'd be happy to do so.

**Comment by stevehipwell** [comment]
@dangoslen you could enable a Dependabot group in this repo and then test it here?

```yaml
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
```

**Comment by dangoslen** [comment]
I believe I have the changes needed for this in `main`. An example is #211 which bumps `jest` and the associated jest types. 

@ChristopherBeltran could you take a look?

**Comment by ChristopherBeltran** [comment]
> I believe I have the changes needed for this in `main`. An example is #211 which bumps `jest` and the associated jest types.
> 
> @ChristopherBeltran could you take a look?

I think we're almost there. I see the entries are duplicated: 
<img width="584" alt="Screenshot 2023-11-27 at 10 55 57 AM" src="https://github.com/dangoslen/dependabot-changelog-helper/assets/34382621/ec4048ce-7818-4ca4-9144-18229c672ee9">

One entry appears to be surrounded by a single ` while the second is surrounded by two ``

**Comment by ChristopherBeltran** [comment]
Great, I think we are good then 👍
