### ISSUE TITLE
Example only works with non-default dependabot.yml

### ISSUE THREAD

**Issue by CramBL** [dangoslen/dependabot-changelog-helper#300]
The example in the README assumes that you configure `dependabot.yml` like you do by specifying that dependabot should use the `dependabot` label on PRs. 

By default dependabot simply uses `dependencies` as a label, and that would be a saner default imo.

I was surprised when I used this action and no changelog entry happened when I used this example, and turns out that the default `activationLabel` makes it silently ignore any `dependabot.yml` configuration that doesn't explicitly configure dependabot to use the label you specify as default for `activationLabel`.

**Comment by dangoslen** [comment]
Hi @CramBL 

Thanks for opening the issue. You are correct that Dependabot doesn't add `dependabot` as a label by default. I avoided using `dependencies` as other possible dependency management tools that could also add that label. I see `dependencies` more as a category and not a good label indicating a workflow to be run. The whole point of the configuration capability is to avoid most of those opinions anyway.

You make a great point that the example makes several assumptions and leads to a new user scratching their heads as to why it didn't "just work". I'll update the example to call out using the `dependencies` label so that at least copy-and-paste scenarios should work easily if you think that is a reasonable step.

I'm hesitant to update the default as it could cause other users to have broken workflows.

**Comment by CramBL** [comment]
I think updating the example would be very helpful yes.

It's a shame that you don't think `dependencies` is a sane default because that means a lot of additional boilerplate for `dependabot.yml` (one per package-ecosystem).

I still think it would be a sane default, and users who want it to only run on the 'dependabot' label could just use the activationLabels to achieve that. 

For us the workflow is already guarded by `if: github.actor == 'dependabot[bot]'` so this is just redundant configuration.

**Comment by dangoslen** [comment]
> a lot of additional boilerplate for dependabot.yml (one per package-ecosystem).

Instead of updating your Dependabot config, you can easily update the `activatoinLabels` here to use `dependencies`. Is that not sufficient?

**Comment by CramBL** [comment]
> > a lot of additional boilerplate for dependabot.yml (one per package-ecosystem).
> 
> Instead of updating your Dependabot config, you can easily update the `activatoinLabels` here to use `dependencies`. Is that not sufficient?

Yes it's acceptable thanks.

**Comment by dangoslen** [comment]
It may be that in a future version, the best approach is to remove the "activation" concept from this action entirely and allow authors to use `if` as needed to decide when to run an action. However, it does require reading and parsing labels.

Another approach may be that 
* if the author is dependabot
* and the `activationLabels` is either empty or the default
* run the action

That I think preserves the current default without breaking other workflows while getting a bit closer to your desired end goal of running the action with no config
